# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ cicd_configuration ]
  pull_request:
    branches: [ cicd_configuration ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          ACTIONS_RUNNER_HOOK_JOB_STARTED: /Users/crura/Documents/bin/ssw
        run: |
          (echo "ssw_path" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/string/strjustify.pro'" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/system/strrep_logenv.pro'" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/string/prstr.pro'" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/genutil/uniqo.pro'" &&
          echo "ssw_path, '/Users/crura/SSW/gen'" &&
          echo "ssw_path, '/Users/crura/SSW/hinode'" &&
          echo "ssw_path, '/Users/crura/SSW/offline'" &&
          echo "ssw_path, '/Users/crura/SSW/proba2'" &&
          echo "ssw_path, '/Users/crura/SSW/sdo'" &&
          echo "ssw_path, '/Users/crura/SSW/site'" &&
          echo "ssw_path, '/Users/crura/SSW/so'" &&
          echo "ssw_path, '/Users/crura/SSW/soho'" &&
          echo "ssw_path, '/Users/crura/SSW/stereo'" &&
          echo "ssw_path, '/Users/crura/SSW/trace'" &&
          echo "ssw_path, '//Users/crura/SSW/vobs'" &&
          echo "ssw_path, '/Users/crura/SSW/packages'" &&
          cat) |
          /Users/crura/Documents/bin/ssw
          # tcsh -c "setenv SSW /Users/crura/SSW"
          # tcsh -c "source /Users/crura/SSW/gen/setup/setup.ssw \loud"
          # tcsh -c "setenv IDL_DIR /Applications/harris/idl88"
          # tcsh -c "setenv FORWARD_WORKING_DIR /Users/crura/SSW/packages/forward"
          # tcsh -c "setenv FORWARD /Users/crura/SSW/packages/forward/idl"
          # tcsh -c "setenv FORWARD_DB /Users/crura/SSW/packages/forward/dbase"
          # tcsh -c "setenv FORWARD_DOCS /Users/crura/SSW/packages/forward/docs"
          # tcsh -c "setenv FORWARD_DB /Users/crura/SSW/packages/forward/dbase"
          # tcsh -c "setenv IDL_PATH +${IDL_DIR}/lib:\+$FORWARD/:\+$FORWARD_DOCS/:\+$FORWARD_DB/:\+$FORWARD_WORKING_DIR/"
          # tcsh -c "setenv IDL_DLM_PATH '/Users/crura/SSW/packages/sunspice/icy/lib:<IDL_DEFAULT>'"
